# Site settings
title: Performance Accountability Council
description: A description of your website that will show up in search indexes and social media shares.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pac.gov" # the base hostname & protocol for your site
logo: 
feature_image: 

colors:
  background: '#ffffff'
  link:
    color: '#0071bc'
    active: '#0071bc'
    hover: '#205493'
    visited: '#0071bc'
  button:
    background: '#0071bc'
    hover: '#205493'
    text: '#fff'
  headers: '#205493'
  text: '#212121'
  reverse_text: '#ffffff'
  projects:
    accent: '#02bfe7'
    card-heading: '#0071bc'
  banner:
    background: '#112e51'
    text: '#fff'
    button:
      background: '#dce4ef'
      text: '#112e51'
  footer:
    primary-background: '#122E51'
    secondary-background: '#122E51'
    text: '#fff'

analytics:
  google:
    code: '' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout:
      - home
      - page
      - "project-list"
      - project
      - "team-list"
      - team

footer:
  image: /assets/img/gsa-logo-dark.jpg
  contact:
    phonenumber: 1-800-CALL-GOV
    email: sample@sample.gov
  text: Performance Accountability Council</a>

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

# Inititalize project and team collections
collections:
  projects:
    output: true
  team:
    output: true

wds-version: 1.1.0
